routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::get('/', 'HomeController');
Route::get('post/{post}', 'Homecontroller@show')->name('post.show');
Route::get('tag/{tagIdOrSlug}', 'Homecontroller@showByTag')->name('tag.show');
Route::get('category/{categoryIdOrSlug}', 'Homecontroller@showByCategory')->name('category.show');
Route::post('subscribe', 'SubsController@subscribe')->name('subscribe');
Route::get('verify/{token}', 'SubsController@verify');

Route::group(['middleware' => 'auth'], function () {
    Route::get('profile', 'ProfileController@index')->name('profile.form');
    Route::post('profile', 'ProfileController@store')->name('profile');
    Route::get('logout', 'AuthController@logout')->name('logout');
    Route::post('comment', 'CommentsController')->name('comment');
});

Route::group(['middleware' => 'guest'], function () {
    Route::get('login', 'AuthController@loginForm')->name('login.form');
    Route::post('login', 'AuthController@login')->name('login');
    Route::get('register', 'AuthController@registerForm')->name('register.form');
    Route::post('register', 'AuthController@register')->name('register');
});


Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'admin'], function () {
    Route::get('/', 'DashboardController')->name('dashboard');
    Route::resource('categories', 'CategoriesController');
    Route::resource('tags', 'TagsController');
    Route::resource('users', 'UsersController');
    Route::resource('posts', 'PostsController');
    Route::get('comments', 'CommentsController@index')->name('comments.index');
    Route::get('comments/toggle/{comment}', 'CommentsController@toggle')->name('comments.toggle');
    Route::delete('comments/{comment}/destroy', 'CommentsController@destroy')->name('comments.destroy');
    Route::resource('subscribers', 'SubscribersController');
});

app/Http/Controllers/SubsController.php
<?php

namespace App\Http\Controllers;

use App\Mail\SubscribeEmail;
use App\Subscription;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;

class SubsController extends Controller
{
    public function subscribe(Request $request)
    {
        $this->validate($request, [
            'email' => ['required', 'email', 'unique:subscriptions']
        ]);

        $subscriber = Subscription::add($request->email);
        $subscriber->generateToken();
        Mail::to($subscriber)->send(new SubscribeEmail($subscriber));

        return redirect()->back()->with('status', 'Check your mail');
    }

    public function verify($token)
    {
        $subscriber        = Subscription::where('token', $token)->firstOrFail();
        $subscriber->token = null;
        $subscriber->save();

        return redirect('/')->with('status', 'Your mail confirmed');
    }
}

resources/views/admin/subs/create.blade.php
@extends('admin.layout')

@section('content')
    <form class="user" action="{{route('subscribers.store')}}" method="post">
        @csrf
        <h3>Add tag</h3>
            @include('admin.errors')
        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="Email">Email</label>
                <input type="text" class="form-control" id="Email" name="email">
            </div>
        </div>
        <div class="form-row justify-content-between">
            <div class="col-md-4">
                <a href="{{route('subscribers.index')}}" class="btn btn-secondary btn-user btn-block">Back</a>
            </div>
            <div class="col-md-4">
                <button type="submit" class="btn btn-primary btn-user btn-block">Submit</button>
            </div>

        </div>

    </form>

@endsection

resources/views/admin/subs/index.blade.php
@extends('admin.layout')

@section('content')

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h3 class="card-title">Simple Full Width Table</h3>
            <a href="{{route('subscribers.create')}}" class="btn btn-success">Add subscriber</a>

        </div>

        <div class="card-body">
            <div class="table-responsive overflow-hidden">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th style="width: 10px">ID</th>
                        <th>email</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tfoot>
                    <tr>
                        <th style="width: 10px">ID</th>
                        <th>email</th>
                        <th>Actions</th>
                    </tr>
                    </tfoot>
                    <tbody>
                    @foreach($subscribers as $subscriber)
                        <tr>
                            <td>{{$subscriber->id}}</td>
                            <td>{{$subscriber->email}}</td>
                            <td>
                                <form action="{{route('subscribers.destroy', $subscriber->id)}}" class="d-inline-block"
                                      method="post">
                                    @csrf
                                    @method('DELETE')
                                    <button onclick="return confirm('are you sure?')" type="submit"
                                            class="btn btn-outline-light px-2">
                                        <i class="fas fa-2x fa-trash-alt text-decoration-none text-danger"></i>
                                    </button>
                                </form>

                            </td>

                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>


@endsection

@section('scripts')



    <script>
        // Call the dataTables jQuery plugin
        $(document).ready(function() {
            $('#dataTable').DataTable();
        });

    </script>


@endsection