routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::get('/', 'HomeController');
Route::get('post/{post}', 'Homecontroller@show')->name('post.show');
Route::get('tag/{tagIdOrSlug}', 'Homecontroller@showByTag')->name('tag.show');
Route::get('category/{categoryIdOrSlug}', 'Homecontroller@showByCategory')->name('category.show');
Route::post('subscribe', 'SubsController@subscribe')->name('subscribe');
Route::get('verify/{token}', 'SubsController@verify');

Route::group(['middleware' => 'auth'], function () {
    Route::get('profile', 'ProfileController@index')->name('profile.form');
    Route::post('profile', 'ProfileController@store')->name('profile');
    Route::get('logout', 'AuthController@logout')->name('logout');
    Route::post('comment', 'CommentsController')->name('comment');
});

Route::group(['middleware' => 'guest'], function () {
    Route::get('login', 'AuthController@loginForm')->name('login.form');
    Route::post('login', 'AuthController@login')->name('login');
    Route::get('register', 'AuthController@registerForm')->name('register.form');
    Route::post('register', 'AuthController@register')->name('register');
});


Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'admin'], function () {
    Route::get('/', 'DashboardController')->name('dashboard');
    Route::resource('categories', 'CategoriesController');
    Route::resource('tags', 'TagsController');
    Route::resource('users', 'UsersController');
    Route::resource('posts', 'PostsController');
    Route::get('comments', 'CommentsController@index')->name('comments.index');
    Route::get('comments/toggle/{comment}', 'CommentsController@toggle')->name('comments.toggle');
    Route::delete('comments/{comment}/destroy', 'CommentsController@destroy')->name('comments.destroy');
    Route::resource('subscribers', 'SubscribersController');
});

app/Tag.php
<?php

namespace App;

use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{

    use Sluggable;

    protected $fillable = ['title'];

    public function resolveRouteBinding($value)
    {
        return  $this->where('slug', $value)->orWhere('id', $value)->firstOrFail();
    }

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];
    }

    public function posts()
    {
        return $this->belongsToMany(Post::class, 'post_tags', 'tag_id', 'post_id');
    }
    public function getImage()
    {
        return $this->image ? '/' . $this->image : '';
    }
}

app/Http/Controllers/Admin/TagsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use App\Tag;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class TagsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tags = Tag::all();
        return view('admin.tags.index', compact('tags'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.tags.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required',
        ]);
        Tag::create($request->all());
        return redirect()->route('tags.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Tag $tag)
    {
        return view('admin.tags.edit', compact('tag'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param Tag $tag
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function update(Request $request, Tag $tag)
    {
        $this->validate($request, [
            'title' => 'required',
        ]);
        $tag->update($request->all());
        return redirect()->route('tags.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Tag $tag
     * @return void
     */
    public function destroy(Tag $tag)
    {
        $tag->delete();
        return redirect()->route('tags.index');
    }
}

resources/views/admin/tags/create.blade.php
@extends('admin.layout')

@section('content')
    <form class="user" action="{{route('tags.store')}}" method="post">
        @csrf
        <h3>Add tag</h3>
            @include('admin.errors')
        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="TagName">Name</label>
                <input type="text" class="form-control" id="TagName" name="title">
            </div>
        </div>
        <div class="form-row justify-content-between">
            <div class="col-md-4">
                <a href="{{route('tags.index')}}" class="btn btn-secondary btn-user btn-block">Back</a>
            </div>
            <div class="col-md-4">
                <button type="submit" class="btn btn-primary btn-user btn-block">Submit</button>
            </div>

        </div>

    </form>

@endsection

resources/views/admin/tags/edit.blade.php
@extends('admin.layout')

@section('content')
    <form class="user" action="{{route('tags.update', $tag)}}" method="post">
        @csrf
        @method('PUT')
        <h3>Update tag</h3>
            @include('admin.errors')
        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="TagName">Name</label>
                <input type="text" class="form-control" id="TagName" name="title" value="{{$tag->title}}">
            </div>
        </div>
        <div class="form-row justify-content-between">
            <div class="col-md-4">
                <a href="{{route('tags.index')}}" class="btn btn-secondary btn-user btn-block">Back</a>
            </div>
            <div class="col-md-4">
                <button type="submit" class="btn btn-primary btn-user btn-block">Submit</button>
            </div>

        </div>

    </form>

@endsection

resources/views/admin/tags/index.blade.php
@extends('admin.layout')

@section('content')

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h3 class="card-title">Simple Full Width Table</h3>
            <a href="{{route('tags.create')}}" class="btn btn-success">Add tag</a>

        </div>

        <div class="card-body">
            <div class="table-responsive overflow-hidden">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th style="width: 10px">ID</th>
                        <th>Name</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tfoot>
                    <tr>
                        <th style="width: 10px">ID</th>
                        <th>Name</th>
                        <th>Actions</th>
                    </tr>
                    </tfoot>
                    <tbody>
                    @foreach($tags as $tag)
                        <tr>
                            <td>{{$tag->id}}</td>
                            <td>{{$tag->title}}</td>
                            <td>
                                <a href="{{route('tags.edit', $tag)}}"
                                   class="btn btn-outline-light px-2">
                                    <i class="fas fa-2x fa-pencil-alt text-decoration-none text-success"></i></a>
                                <form action="{{route('tags.destroy', $tag->id)}}" class="d-inline-block"
                                      method="post">
                                    @csrf
                                    @method('DELETE')
                                    <button onclick="return confirm('are you sure?')" type="submit"
                                            class="btn btn-outline-light px-2">
                                        <i class="fas fa-2x fa-trash-alt text-decoration-none text-danger"></i>
                                    </button>
                                </form>

                            </td>

                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>


@endsection

@section('scripts')



    <script>
        // Call the dataTables jQuery plugin
        $(document).ready(function() {
            $('#dataTable').DataTable();
        });

    </script>


@endsection